services:
  tailscale:
    image: tailscale/tailscale
    restart: always
    ports: [ "${TS_PORT:-4164}:4164" ]
    volumes:
      - ./tailscale:/var/lib/tailscale:rw
      - ${PWD}/tailscale_serve.json:/config/serve.json:ro
    environment:
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_HOSTNAME=${TS_HOSTNAME:-${COMPOSE_PROJECT_NAME}}
      - TS_STATE_DIR=/var/lib/tailscale
    networks:
      - app_network
    cap_add:
      - net_admin
      - sys_module

  blackcandy:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: service:tailscale
    restart: always
    volumes:
      - ./config:/app/config
      - /Users/m/Music/BlackCandy:/music_files
    environment:
      - HOST=${HOSTNAME}
      - MEDIA_PATH=/music_files

networks:
  app_network:
    name: ${COMPOSE_PROJECT_NAME}-network
    driver: bridge

volumes:
  tailscale: {}
